FROM node:lts-stretch
WORKDIR /usr/app/
COPY ./app/package.json  ./

RUN npm install
RUN mkdir uploads

COPY ./docker/resources/app/entrypoint.sh  ../../
RUN chmod +x /entrypoint.sh

EXPOSE 3000

CMD ["sh", "/entrypoint.sh"]